
import __ASTRO_IMAGE_IMPORT_1XEVHv from "./images/dashboard-file-menu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_Z2s3NRF from "./images/dashboard-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_ZFDKS1 from "./images/dashboard-project-card-menu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_Z1jaKmR from "./images/dashboard-project-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_Z1yRLgO from "./images/login-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md";
import __ASTRO_IMAGE_IMPORT_xjEcR from "./images/metamodel-editor-class-properties.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md";
import __ASTRO_IMAGE_IMPORT_1nqVR2 from "./images/metamodel-editor-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md";
import __ASTRO_IMAGE_IMPORT_ZuFhd9 from "./images/metamodel-editor-palette.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md";
import __ASTRO_IMAGE_IMPORT_JvFuD from "./images/metamodel-editor-reference-properties.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md";
import __ASTRO_IMAGE_IMPORT_Z2b6b4C from "./images/metamodel-editor-three-classes.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md";
import __ASTRO_IMAGE_IMPORT_Z2mBzyL from "./images/metamodel-editor-tree-view.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md";
import __ASTRO_IMAGE_IMPORT_1F12gf from "./images/model-editor-person-address.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md";
import __ASTRO_IMAGE_IMPORT_1oMrVY from "./images/new-project-dialog.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md";
import __ASTRO_IMAGE_IMPORT_Z1raKkj from "./images/new-project-dialog.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_VnHec from "./images/password-recovery-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md";
import __ASTRO_IMAGE_IMPORT_Z8OCG3 from "./images/registration-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md";
import __ASTRO_IMAGE_IMPORT_fVPVq from "./images/rendered-class-diagram.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md";
export default new Map([["./images/dashboard-file-menu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_1XEVHv], ["./images/dashboard-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_Z2s3NRF], ["./images/dashboard-project-card-menu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_ZFDKS1], ["./images/dashboard-project-card.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_Z1jaKmR], ["./images/login-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md", __ASTRO_IMAGE_IMPORT_Z1yRLgO], ["./images/metamodel-editor-class-properties.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md", __ASTRO_IMAGE_IMPORT_xjEcR], ["./images/metamodel-editor-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md", __ASTRO_IMAGE_IMPORT_1nqVR2], ["./images/metamodel-editor-palette.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md", __ASTRO_IMAGE_IMPORT_ZuFhd9], ["./images/metamodel-editor-reference-properties.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md", __ASTRO_IMAGE_IMPORT_JvFuD], ["./images/metamodel-editor-three-classes.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md", __ASTRO_IMAGE_IMPORT_Z2b6b4C], ["./images/metamodel-editor-tree-view.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fmetamodel-editor.md", __ASTRO_IMAGE_IMPORT_Z2mBzyL], ["./images/model-editor-person-address.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md", __ASTRO_IMAGE_IMPORT_1F12gf], ["./images/new-project-dialog.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md", __ASTRO_IMAGE_IMPORT_1oMrVY], ["./images/new-project-dialog.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fuser-guide%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_Z1raKkj], ["./images/password-recovery-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md", __ASTRO_IMAGE_IMPORT_VnHec], ["./images/registration-form.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Fsign-in.md", __ASTRO_IMAGE_IMPORT_Z8OCG3], ["./images/rendered-class-diagram.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Ffirst-project.md", __ASTRO_IMAGE_IMPORT_fVPVq]]);
		